// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://farbrlngirozwtxyprgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhcmJybG5naXJvend0eHlwcmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjM1MTMsImV4cCI6MjA3MzQ5OTUxM30.tG6j_23mTIEV6D6iL2vOa2-i2wTMU-C6uclmvLU7R0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});